### ISSUE TITLE
Sensor stopped working ~ 13.04.2024 ☹

### ISSUE THREAD

**Issue by MartaSien** [hs3city/kingbob-plant-sensor#3]
This is a screenshot from sensor reading from HS3 Home Assistant. There are no reading after around 13.04.2024.
![image](https://github.com/hs3city/kingbob-plant-sensor/assets/86041155/31b0a81a-d9a1-4637-b84d-77466afbe51b)

**Comment by DoomHammer** [comment]
Yeah. That's cause The Count stopped working and @reinhrst seems to be the only person with access to the logs.

**Comment by MartaSien** [comment]
Current status: sensor is working 😃 but callibration for detecting soil moisture still requires more work.
